# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: packages.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class User(betterproto.Message):
    id: int = betterproto.int32_field(1)
    username: str = betterproto.string_field(2)
    password: str = betterproto.string_field(3)


@dataclass
class Movie(betterproto.Message):
    id: int = betterproto.int32_field(1)
    title: str = betterproto.string_field(2)
    cover: bytes = betterproto.bytes_field(3)
    value: float = betterproto.float_field(4)
    year: str = betterproto.string_field(5)
    director: str = betterproto.string_field(6)
    sinopse: str = betterproto.string_field(7)


@dataclass
class Movies(betterproto.Message):
    movies: List["Movie"] = betterproto.message_field(1)


@dataclass
class Rental(betterproto.Message):
    user_id: int = betterproto.int32_field(1)
    movie_id: int = betterproto.int32_field(2)
