# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: package.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class User(betterproto.Message):
    name: str = betterproto.string_field(1)
    email: str = betterproto.string_field(2)
    address: str = betterproto.string_field(3)


@dataclass
class UserList(betterproto.Message):
    users: List["User"] = betterproto.message_field(1)
